### ISSUE TITLE
TypeError: 'module' object is not callable`

### ISSUE THREAD

**Issue by ebagjones** [kristpapadopoulos/seriesnet#2]
This sounds pretty interesting, but I get this when I try to run it on a simple 1D array:
`Traceback (most recent call last):
  File ".\seriesnet.py", line 130, in <module>
    print(evaluate_timeseries(np.arange(100),10))
  File ".\seriesnet.py", line 107, in evaluate_timeseries
    model = DC_CNN_Model(length)
  File ".\seriesnet.py", line 67, in DC_CNN_Model
    l1a, l1b = DC_CNN_Block(32,2,1,0.001)(input)
  File ".\seriesnet.py", line 56, in f
    network_out = merge([residual, network_in], mode='sum')
TypeError: 'module' object is not callable`

**Comment by kristpapadopoulos** [comment]
Thanks this is corrected by updating Keras merge with Keras Add in new version of Keras.  This has been implemented.
