### ISSUE TITLE
Test example

### ISSUE THREAD

**Issue by saubersf** [kristpapadopoulos/seriesnet#3]
Can you please provide an example of how to run the code?
I tried:
` a = np.array([0,1,2,3,4,5])
  evaluate_timeseries(a , 1)
 `
but it doesn't work.

**Comment by kristpapadopoulos** [comment]
This is correct way to run it.  This should run - there was an issue with Keras merge layer that has now been replaced with Add but this timeseries may not produce meaningful results even it runs.

Each layer in the Dilated Convolution layer block has a dilated rate that looks back in time.  The number of layers plus the dilation rate need to be adjusted to optimize for shorter length time series. 

In the paper - the baseline code with seemed to work well on time series 108 or 64 time steps with 7 layers up to dilation rate of 64.

**Comment by RoyalTS94** [comment]
Hey, thanks for this great code! As for saubersf running a simple example does not work for me. I get an error for the model.fit(X,y) call in line 127. Error message is "ValueError: None values not supported." Do you know how to solve this error?
