### ISSUE TITLE
Understanding output of the model of shapes

### ISSUE THREAD

**Issue by MohamedLotfyElrefai** [kristpapadopoulos/seriesnet#7]
I don't understand something you are making output  as (NONE,length,1) but you take only the last point and your y_output data is only one point shifted from your input data for example:
>x=[0,1,2,3,4,5,...63]
>y=[64]

why not making only a flatten layer and dense layer for getting the output of this point ?
will it make a big difference ?

**Comment by kristpapadopoulos** [comment]
using the convolutions requires a shape like this with timesteps of length and dim = 1.  Not sure i understand but the y is the target for the predictions during training, so its shifted by one since we are trying to predict the next time step.
