### ISSUE TITLE
Simpe test example

### ISSUE THREAD

**Issue by RoyalTS94** [kristpapadopoulos/seriesnet#8]
Hey, thanks for this great code! As for saubersf running a simple example does not work for me. I get an error for the model.fit(X,y) call in line 127. Error message is "ValueError: None values not supported." Do you know how to solve this error?

**Comment by lgq1997** [comment]
Hey, I also encountered this problem, did you solve it?

**Comment by gouravvemula0** [comment]
change optimizers.Adam(lr=0.00075, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False)  to optimizers.Adam(lr=0.001)

**Comment by lgq1997** [comment]
> 将优化器更改为优化器.Adam（lr = 0.00075，beta_1 = 0.9，beta_2 = 0.999，epsilon = None，衰减= 0.0，amsgrad = False）更改为优化器.Adam（lr = 0.001）

The problem is solved，thank you very much!
