### ISSUE TITLE
Has you paper been published?

### ISSUE THREAD

**Issue by kumar10725** [kristpapadopoulos/seriesnet#9]
That's a great architecture you have there. I wanted to know if your paper has been published? so, that I may add to references of my paper. Thanks.

**Comment by Nestak2** [comment]
Hi @kumar10725 , sorry for not being on-topic but I have noticed that kristooaoadopoulos doesn't answer the issue's here. So, I wonder have you used this code also for multivariate predictions? I am looking for a model to predict air pollution and I am having as input data timer series of the air pollution itself, the outside temperature, wind speed, humidity and other meteorological data. If you can provide me with some multivariate model or suggest me how to alter this one it would be highly appreciated. Cheers

**Comment by kumar10725** [comment]
Hello there @Nestak2, I found the model developed by @kristpapadopoulos to be a great inspiration and I have borrowed and concept and developed a unet architecture for wind speed prediction. For multivariate dataset, you can still use this architecture. You may have to modify the filter and kernel size. You can use multiple of 3. I found this model to work great with sliding window prediction technique.

Hope this helps and I would like to thank @kristpapadopoulos  for a such a great work.

**Comment by Nestak2** [comment]
@kumar10725 Thanks for the answer! Have you done your windspeed prediction in a multivariate manner? I guess this would only make sense because the wind speed is correlated to air pressure, temperature, sun irradiation (or alternatively cloud cover), precipitation a.s.o. I would like to have a look at your architecture, in case it is published on github or somewhere else! thanks

**Comment by kumar10725** [comment]
> @kumar10725 Thanks for the answer! Have you done your windspeed prediction in a multivariate manner? I guess this would only make sense because the wind speed is correlated to air pressure, temperature, sun irradiation (or alternatively cloud cover), precipitation a.s.o. I would like to have a look at your architecture, in case it is published on github or somewhere else! thanks

In fact, I just used the historical data for making prediction. As you said using multi-variate data would make better sense but, it is not practical in remote areas as, it increases the number of sensors and also more variables will increase the overall computation time. If you are interested in multi-variate prediction. You might have to try adjusting the hyperparameters yourself.

**Comment by kristpapadopoulos** [comment]
@kumar10725 thanks for the interest in the paper and work here.  Sorry for the delay but I have not published the paper before.

**Comment by pedroyzkrak** [comment]
@kristpapadopoulos 
Why isn't this paper published?

**Comment by kristpapadopoulos** [comment]
@pedroyzkrak  Hi thanks for the interest,  I did not have a chance to publish as I got busy with other things.  It posted the paper to github when it was completed to share.
